### ISSUE TITLE
run multiple pocs error

### ISSUE THREAD

**Issue by nu0l** [WAY29/pocV#2]
./pocV run -t http://example.com -P /root/pocV/xray/pocs/*
./pocV run -t http://example.com -p /root/pocV/xray/pocs/*
![Uploading 截屏2022-02-23 下午3.47.03.png…]()

**Comment by nu0l** [comment]
<img width="1433" alt="截屏2022-02-23 下午3 47 03" src="https://user-images.githubusercontent.com/54735907/155279383-fd3c5fd9-cc46-444c-81d3-76c017768cba.png">

**Comment by WAY29** [comment]
Please check whether your version is up-to-date first. I did not have the problem of incorrect usage in my local test

**Comment by WAY29** [comment]
This bug should be caused by the parameter /root/pocv/xray/pocs/* without double quotation marks. Please try  `./pocV run -t http://example.com/ -P "/root/pocV/xray/pocs/*"`.
I will update README.md soon.
