### ISSUE TITLE
能否增加 webhook功能？

### ISSUE THREAD

**Issue by aiwennba** [WAY29/pocV#3]
增加 webhook功能，对接微信、钉钉消息提醒

**Comment by WAY29** [comment]
实际上只要简单地修改pkg/common/structs/output.go中的代码，实现Output接口，修改internal/output/output.go中将新实现的结构体注入到outputs中即可实现你的需求。本代码只作为学习使用，如果你想实现的话欢迎fork并pr，而且我也觉得这个功能并不一定需要从pocV中实现。

**Comment by WAY29** [comment]
实际上我建议寻找/编写一个其他的监控项目，监控文件写入，过滤内容并告警

**Comment by aiwennba** [comment]
> 实际上只要简单地修改pkg/common/structs/output.go中的代码，实现Output接口，修改internal/output/output.go中将新实现的结构体注入到outputs中即可实现你的需求。本代码只作为学习使用，如果你想实现的话欢迎fork并pr，而且我也觉得这个功能并不一定需要从pocV中实现。

好的，感谢

**Comment by WAY29** [comment]
> > 实际上只要简单地修改pkg/common/structs/output.go中的代码，实现Output接口，修改internal/output/output.go中将新实现的结构体注入到outputs中即可实现你的需求。本代码只作为学习使用，如果你想实现的话欢迎fork并pr，而且我也觉得这个功能并不一定需要从pocV中实现。
> 
> 好的，感谢

可以试试我新写的工具: https://github.com/WAY29/FileNotifier
