### ISSUE TITLE
短路逻辑Bug

### ISSUE THREAD

**Issue by lanyi1998** [WAY29/pocV#5]
按照短路逻辑，r1不应该被执行。这样会造成大量无意义的扫描请求

![31691646456546_ pic](https://user-images.githubusercontent.com/31091395/156868861-5e053988-584e-4cf7-986d-781bbfabf1a6.jpg)

**Comment by WAY29** [comment]
我会在下个版本修复

**Comment by WAY29** [comment]
请查看最新版本(3.6.0)
